### ISSUE TITLE
getting nan values after some iterations

### ISSUE THREAD

**Issue by sergulaydore** [y0ast/Variational-Autoencoder#5]
I am trying this method for neuroimaging data but I am getting nan values after some iterations. What would be the reason for this? I'll appreciate your help.
Thanks!

**Comment by y0ast** [comment]
Unfortunately the VAE does not work particularly well on data where n << d, such as neuroimaging data. There is ongoing research to combat this, but for now I would recommend trying other methods.

As for the reason of the NaN, it's probably the KL divergence blowing up, because the variance is huge.

**Comment by lucky6qi** [comment]
I also have the same problem using different input data. I'm not sure about the reason.

Is the huge variance caused by the randomness of observed variable _x_? (there is a large amount of very different _x_ result in the same latent variable _z_.)

Thanks for your help!

**Comment by y0ast** [comment]
It's mainly caused by the fact that inference (finding q(z|x)) is probably very hard for your problem. This results in large variances, which in turn results in a large KL divergence. You could try with a wider prior on q(z) (essentially softening regularizing grip of the KLD), see also: http://arxiv.org/abs/1511.05644

**Comment by esizikova** [comment]
@y0ast Is there a reference you could point me about the challenges of VAEs in the case of  n << d? 
Thanks!

**Comment by y0ast** [comment]
Nothing more specific than what a google scholar would turn up I'm afraid.

**Comment by ppkn** [comment]
@y0ast what would the code modified code look like for a wider prior? I'm trying to figure out exactly where that would fit in.

**Comment by y0ast** [comment]
The easiest way is to decrease the `0.5` at the definition of KLD. It's not exactly equivalent to a wide prior, but very easy to do.

**Comment by shengchiliu** [comment]
@y0ast may I ask you that the n and d in "n << d " refer to?
is n the dataset size??

**Comment by y0ast** [comment]
`n` is dataset size, `d` is dimensionality of the data
